### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by mkrudele** [ibm-cloud-docs/account#1]
The Search API link is broken.  
<img width="533" alt="image" src="https://user-images.githubusercontent.com/11750429/221522810-d6a32cb2-c073-4313-bd1d-cb06de05f2e7.png">

**Comment by KentHall2018** [comment]
I'll take this one since it involves changes that I recently made.

**Comment by KentHall2018** [comment]
updated the link. everything should be good now. closing.
