### ISSUE TITLE
Missing CLI example for creating a service ID API key.

### ISSUE THREAD

**Issue by silliman** [ibm-cloud-docs/account#1]
The CLI version of the page "Managing service ID API keys" is missing an example for creating a service ID API key.

https://cloud.ibm.com/docs/account?topic=account-serviceidapikeys&interface=cli&code=java

**Comment by addison-martin1** [comment]
@silliman The CLI command for creating a service ID API key is now available in that topic: https://cloud.ibm.com/docs/account?topic=account-serviceidapikeys&interface=cli#create_service_key_cli
