### ISSUE TITLE
https://ibm.biz/account_transfer

### ISSUE THREAD

**Issue by roli667** [ibm-cloud-docs/account#1]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by hooznora** [comment]
Hello @roli667,
How can we help you? Please provide some more details by answering the following questions:

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?
