### ISSUE TITLE
Cloud Account - Watson Assitant

### ISSUE THREAD

**Issue by LanaRobertaKoutsoukos** [ibm-cloud-docs/account#10]
1. What are the details of the issue you're experiencing? I can not use Watson Assistant because I have this message:
You do not have a resource group. To create a resource group, go to Manage - Account - Resource Groups from the header.
I already upgraded my account to a Lite account but still don't have access to resources

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/catalog/services/watson-assistant

3. Do you have a suggestion about how to resolve the issue? NO

**Comment by mekaufman** [comment]
@LanaRobertaKoutsoukos All accounts have a default resource group by default. Are you trying to create a plan of Watson Assistant that is not a Lite plan? If you are in your own account, then you should have full access to your default resource group as well as the ability to provision resources from the catalog that fit the criteria of your account type. 

There is not a documentation update that I can make based on your issue at this time. Please reach out to support if you continue to experience issues with your account.
