### ISSUE TITLE
Query from customer How to update the time zone in Cloud Account.Is it possible?

### ISSUE THREAD

**Issue by testrashmi** [ibm-cloud-docs/account#10]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

Provide more information on the timezone update

My understanding is :
On an account level its not possible, some services do have the option to provide logs in local time but it varies depending on the service.

**Comment by hooznora** [comment]
@testrashmi Thank you for forwarding the query. Checked the followings to see if the timezone update is possible on the account level:

- At the first step, while creating a new account there is no option for timezone setting, only for choosing a country/region. After creating the account, there isn't a specific setting for updates in the console either. 
- As you mentioned in the issue, there are services that require location info for e.g. monthly prices that are different for each country. Based on these, it seems that there is no timezone setting on account level.

Please let me know if you have any further questions.

**Comment by KentHall2018** [comment]
@hooznora can this issue be closed?

**Comment by KentHall2018** [comment]
Nora said this issue can be closed.
