### ISSUE TITLE
broken link  for 'Account types' hyperlink 

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/account#11]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
broken link in:
https://cloud.ibm.com/docs/account?topic=account-accountfaqs#changeacct
for: '[Account types](https://cloud.ibm.com/docs/account?topic=account-liteaccount)
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-accountfaqs#changeacct
![image](https://user-images.githubusercontent.com/131889203/234642436-ac2b2ea8-ca03-46e1-b7ca-b3ab6525cb22.png)
![image](https://user-images.githubusercontent.com/131889203/234642458-b7ef621c-bb28-4bb5-b217-28ff5fb43b0d.png)

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
Thank you for the feedback! The link has been updated.
