### ISSUE TITLE
Suggest adding a note: User preferences do not affect the Notifications Distribution List in any way. 

### ISSUE THREAD

**Issue by Ketcomp** [ibm-cloud-docs/account#11]
https://cloud.ibm.com/docs/account?topic=account-email-prefs#setting-platform-notifications

The notifications distribution list is not affected by your user/email preferences - they shouldn't be because the email addresses on this list are not necessarily part of any IBM account - but this is confusing to users nevertheless. 

Both on the tool itself and in the Docs, this could be clarified in greater detail.

**Comment by hlucey** [comment]
Content updates drafted and issue already opened to track progress.
Reached out to @Ketcomp.
