### ISSUE TITLE
Financial Services Validated 

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/account#11]
Can you please describe in detail what Financial Service Validated means? 
The only info that is documented is this:
_"Services that are designated as IBM Cloud for Financial Services Validated leverage the industry’s highest levels of encryption certification, provides preventive and compensatory controls for financial services regulatory workloads, multi-architecture support and proactive, and automated security."_

What kind of industry levels are supported? Please describe a little bit more details. Otherwise it doesn't make sense to have such services.

**Comment by knee-nah** [comment]
Hi @ThomasUllrich666, thanks for sharing this feedback, and apologies for the delayed response! We recently re-vamped our Financial Services Validated documentation, you can get started with it here: https://cloud.ibm.com/docs/framework-financial-services?topic=framework-financial-services-about

We also included links to that set of documentation in this topic as well: https://cloud.ibm.com/docs/account?topic=account-enabling-fs-validated

I hope this helps you find the information you need about the IBM Cloud Framework for Financial Services! Thanks again for sharing your feedback.
