### ISSUE TITLE
display name and display id of iam roles are not properly mapped

### ISSUE THREAD

**Issue by kavya498** [ibm-cloud-docs/account#11]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Users are unable to identify exact role when they try to to assign policy via terrform or through APIs 
UI shows display name , where as APIs actually take Ids

UI scrnshot
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/46739084/150287890-c7dee140-265a-4baf-abd8-f8625610916d.png">

Docs scrnshot
<img width="990" alt="image" src="https://user-images.githubusercontent.com/46739084/150287829-eb3d02d2-530f-41ab-9012-e6ca4cb798ce.png">

Ideally `Satellite Link Administrator` role that is shown in UI page and `Satellite Link Source and Endpoint Controller` that is present in docs are same..  UI shows display names where as Docs gives info about display ID..This mapping is not properly documented, which leads to confusion..
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-iam-service-roles-actions#satellite
3. Do you have a suggestion about how to resolve the issue?
I believe current docs gives info about role Id and description, It would be nice if one more column is added that gives display name details to avoid confusions..

Thanks

**Comment by mekaufman** [comment]
@kavya498 Thank you for this useful feedback. I'd like to move this issue, so I will be reaching out with additional details as to what we have planned to address this to help customers identify the ID used API.

I did want to note that from the Roles UI page, you can use the List of actions (3 dot) menu from the column for the row that you want to identify an ID for and click Details and you will see the CRN value that includes the ID. So it is available from the UI, but I agree that we need draw attention to this, which is what our internal issue will address.

View details panel in UI:
![image](https://user-images.githubusercontent.com/13648625/151616010-cc0a4ca3-7441-4f2f-b225-4a97afaed79d.png)
