### ISSUE TITLE
Bad link in tip to transfer individual resource to another account

### ISSUE THREAD

**Issue by herbeck558** [ibm-cloud-docs/account#12]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Trying to follow the tip for transferring a single resource on this page ends up just pushing down to transferring the full account on the same page.
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-transfer
3. Do you have a suggestion about how to resolve the issue?
Fix the link to point to the ibmcloud catalog command reference detailing how to transfer a single resource.

**Comment by hlucey** [comment]
Addressed and updated documentation.

**Comment by herbeck558** [comment]
@hlucey you removed the tip.  So where is the doc on how to transfer a resource to another account? We need to know how to do this.
