### ISSUE TITLE
Broken link for: [cli documentation]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/account#12]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

broken link for: [cli documentation](https://cloud.ibm.com/docs/account?topic=cli-manage-catalogs-plugin#create-catalog)
https://cloud.ibm.com/docs/account?topic=account-create-private-catalog&interface=cli

2. Is this issue in reference to a specific page? If so, please provide a link.
![image](https://user-images.githubusercontent.com/131889203/234652342-9a41a35e-c6f9-49c4-8fea-00b8279b1e73.png)
![image](https://user-images.githubusercontent.com/131889203/234652355-a92f3932-38c5-4477-80f8-cbe2c967fa6b.png)

3. Do you have a suggestion about how to resolve the issue?

**Comment by cairey81** [comment]
@rodrigolara1 Thank you for the feedback! I've updated the link in the documentation.
