### ISSUE TITLE
crn

### ISSUE THREAD

**Issue by Sherpa99** [ibm-cloud-docs/account#13]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by reka94** [comment]
Hello @Sherpa99, are you facing any doc related issues we can help you with?

**Comment by reka94** [comment]
I'm closing this issue. Feel free to open a new one and include more details, if you still need our help.
