### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by frafazioIBM** [ibm-cloud-docs/account#14]
In this page: https://cloud.ibm.com/docs/account?topic=account-account-getting-started#signup-federated is linked a guide to deep dive that reference tu a box link that doesn't work: https://ibm.ent.box.com/notes/78040808400?v=IBMid-Federation-Guide

**Comment by addison-martin1** [comment]
Hi @frafazioIBM, 

The IBMid Enterprise Federation guide has moved to a new location: https://www.ibm.com/docs/en/ief. We've updated our documentation with the right link.
