### ISSUE TITLE
Documented 720 hour limits on IAM tokens 

### ISSUE THREAD

**Issue by rjminsha** [ibm-cloud-docs/account#16]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
https://cloud.ibm.com/docs/account?topic=account-token-limit documents 720 hours / 30 days as the limit.  I believe that has has been changed to 72.  

```
Enter the time limit in hours. A refresh token can be valid for up to 720 hours (30 days).
```

3. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-token-limit

4. Do you have a suggestion about how to resolve the issue?
Verify if documentation is still current.

**Comment by mekaufman** [comment]
Thanks @rjminsha. I verified that is correct and have made the update to the documentation.
