### ISSUE TITLE
Not able to login to my Cloud Account

### ISSUE THREAD

**Issue by AishwaryaND** [ibm-cloud-docs/account#16]
I am not able to login to IBM cloud. Its asks for a code from a 2 factor authentication app.
Though I haven’t set up the 2 factor authentication app, it says already setup and is not allowing me to setup one

**Comment by AishwaryaND** [comment]
![Uploading Screenshot 2021-01-25 at 11.52.25 PM.png…]()

**Comment by AishwaryaND** [comment]
<img width="692" alt="Screenshot 2021-01-26 at 12 00 23 AM" src="https://user-images.githubusercontent.com/39726899/105749502-7ee3df80-5f69-11eb-9601-ae9c75b2bd26.png">

**Comment by AishwaryaND** [comment]
The above screenshot is after setting up a 2 factor authentication app and using the access code generated there

**Comment by reka94** [comment]
Hello @AishwaryaND! This repository is for reporting issues with documentation. If you're facing issues with your login, please contact IBM Cloud support to find a solution for your problem. https://cloud.ibm.com/docs/get-support?topic=get-support-get-supportfaq
