### ISSUE TITLE
Bug: with the migration to Secrets Manager, obtaining the cluster TLS certificate fails

### ISSUE THREAD

**Issue by ecejjar** [ibm-cloud-docs/account#17]
Going through https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#priv-se-priv-controller-2 (step 2):

In IBM Cloud-provided ROKS clusters, Certificate Manager (CM) has been deprecated in favor of Secrets Manager (SM). New clusters are by default provisioned using SM as certificate store.

With SM, the procedure using `ibmcloud oc ingress secret create --cert-crn` to copy the cluster certificate to the local ingress fails:

```Error retrieving secret from the IBM Cloud Secret Manager instance. Try again later. (ECSRCGC) Incident ID: 53e294fe-cd09-460d-899b-fb8950066eb5```

The procedure needs to be updated to adapt to the new restrictions imposed by SM.

**Comment by mekaufman** [comment]
Hi @ecejjar I've opened the issue for the team that can look into your feedback here: https://github.com/ibm-cloud-docs/openshift/issues/114
