### ISSUE TITLE
IBM cloud 

### ISSUE THREAD

**Issue by WeddyNkatha265** [ibm-cloud-docs/account#18]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by KentHall2018** [comment]
@loveyourplane thanks for opening this issue but it looks like there's no actionable information provided. feel free to open another issue if you have feedback about the documentation.
