### ISSUE TITLE
DB2Warehouse scale permission docs confusing

### ISSUE THREAD

**Issue by ezberg2** [ibm-cloud-docs/account#19]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
 The DB2Warehouse documentation seems to have incorrect information.  It shows that the Editor role has the scale operation as part of it, but this must be explicitly granted.  This is not obvious in the documentation and has cause confusion for customers

3. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/account?topic=account-iam-service-roles-actions#dashdb-roles
In this documentation you will see in 'Actions' 'dashdb.console.scale' includes the Editor role, but this must be explicitly granted INSTANCE_SCALE

5. Do you have a suggestion about how to resolve the issue?

May need to remove the Editor role as being included in the dashdb.console.scale action

**Comment by addison-martin1** [comment]
Hi @ezberg2, thank you for reaching out. The correct team has been made aware of this issue.
