### ISSUE TITLE
Update Request for 'https://cloud.ibm.com/docs/account?topic=account-transfer&locale=en#transfer-lost''

### ISSUE THREAD

**Issue by kmatsuok** [ibm-cloud-docs/account#2]
Currently this page (https://cloud.ibm.com/docs/account?topic=account-transfer&locale=en#transfer-lost) says ' If they already own an IBM Cloud account, you can request to move the account that they currently own to another user or cancel the account.'

However I think recent system update allows all users have multiple cloud accounts now, this sentence should be removed or updated at least.  

Please check and update document as it gives the impression that the new owner-to-be can't be the owner of another IBM Cloud account.

**Comment by hlucey** [comment]
Sentence was removed since users can own multiple accounts.
