### ISSUE TITLE
Subscription conversion to Paygo - including VAD

### ISSUE THREAD

**Issue by ascarder** [ibm-cloud-docs/account#21]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing? _We receive a lot of credit requests from VADs/BPs when they are the payer of an expired subscription because they aren't receiving any notification email about the PayGO conversion Automation despite the Renewal type is set to end of terms._

2. Is this issue in reference to a specific page? If so, please provide a link. _It should be better indicated into the Subscription section that the conversion is for any account included those handled by VAD o BP_

3. Do you have a suggestion about how to resolve the issue? _Sending a notification email about expired subscription to Payer (VADs/BPs) allows them to confirm a termination account or proceed with PAYG transition against the EndUser
To add VADs/BPs in CC list of the actual notification email about the expiration date of subscription._

**Comment by hlucey** [comment]
Hi @ascarder, 

Thank you for opening this issue. Our billing team has been working to resolve this issue and plans to rollout updates in the near future. In the meantime, we created an email that is sent to VADs/BPs and the end customer regarding the conversion process.
