### ISSUE TITLE
Broken Link on page - FAQs about managing resources

### ISSUE THREAD

**Issue by dhoop39** [ibm-cloud-docs/account#21]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
 - link on a page goes to a document no longer available.  The FAQ related to Reclamation provides a link to "Working with resources and resource groups" that returns Sorry, this content isn't available.  
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-resources-faq&interface=cli#reclamation-list
3. Do you have a suggestion about how to resolve the issue?
Update the URL Link.

**Comment by addison-martin1** [comment]
Hi @dhoop39, thank you for opening an issue. This broken link has been fixed.
