### ISSUE TITLE
How do I find the If-Match: {if_match} value?

### ISSUE THREAD

**Issue by vanadiscrawford** [ibm-cloud-docs/account#23]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

I am trying to use the CBR API to update a zone an `If-Match` is required. However, the APIDOC is unhelpful in determining this value and this topic doesn't give any assistance either,

3. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/account?topic=account-context-restrictions-update&interface=api

5. Do you have a suggestion about how to resolve the issue?

Clariify in both the APIDOC and this topic how one determines the `If-Match` value for a zohe.

**Comment by addison-martin1** [comment]
Thank's for reaching out about this @vanadiscrawford. I've opened an issue on my end to address this.
