### ISSUE TITLE
Missing example for endpoint type (and other possible contexts) in the API version of doc

### ISSUE THREAD

**Issue by vanadiscrawford** [ibm-cloud-docs/account#24]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
In trying out the CBR API I was trying to configure a rule for private endpoints only (similar to the example provide for the CLI).  The API version of the documentation does not provide an example for this scenario and various options I tried just did not work.  The API doc also does not provide information on the various valid context values and only provides the length and characters that can be specified

![image](https://github.com/ibm-cloud-docs/account/assets/66632264/8dff9e4e-51d9-449b-823f-6b5eb252211d)

3. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-context-restrictions-create&interface=api

5. Do you have a suggestion about how to resolve the issue?
All possible API values should be documented in the main subcollection and the API doc.

**Comment by addison-martin1** [comment]
Hi @vanadiscrawford, I've opened an issue on my end to fix this. Thanks!
