### ISSUE TITLE
cloud foundry organization name creation

### ISSUE THREAD

**Issue by Meianandavel** [ibm-cloud-docs/account#24]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
Hi @Meianandavel I see you that you might have a question regarding creating organization names. You can find the documentation for creating orgs here: https://cloud.ibm.com/docs/account?topic=account-orgsspacesusers&interface=ui#createorg. Please let us know if you're experiencing any other issue with the documentation.
