### ISSUE TITLE
IAM Trusted Profiles page needs to be enriched with those two profiles

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/account#25]
The documentation about IAM Trusted Profiles available at https://cloud.ibm.com/docs/account?topic=account-trusted-profile-update&interface=ui
needs to be enriched with those two tutorials
- [Using Trusted Profiles in your Kubernetes and OpenShift Clusters](https://www.ibm.com/cloud/blog/using-trusted-profiles-in-your-kubernetes-and-openshift-clusters)
- [Introducing Trusted Profiles for VPC Virtual Server Instances](https://www.ibm.com/cloud/blog/introducing-trusted-profiles-for-vpc-virtual-server-instances)

Today, the documetation is too high level. The page should embed those two tutorials.
@addison-martin1

**Comment by addison-martin1** [comment]
Hi @lionelmace, thanks for the feedback. These two blogs are now linked in the trusted profiles tutorial for compute resources here: https://cloud.ibm.com/docs/account?topic=account-trustedprofile-compute-tutorial&interface=ui#iam-compute-next. I just made this update, so it might take a few minutes to render.
