### ISSUE TITLE
Not able to find 'Default' resource group

### ISSUE THREAD

**Issue by TusharPuri10** [ibm-cloud-docs/account#25]
Not able to find 'Default' resource group in Resource groups (Manage > Account > Resource Groups).
Account Type: Trial (Free)

Resource Group Section showing the following things:

**No search results
There were no results for ""**

but on clicking on 'create' button in right panel. It is showing the following things:

**Resource group quota reached
Your Lite account quota is one resource group.
Ready to add more? Upgrade to a Pay-As-You-Go account.** @hlucey

**Comment by addison-martin1** [comment]
Hi @TusharPuri10, is it possible that the Default resource group was renamed? For more information, see [Renaming a resource group](https://cloud.ibm.com/docs/account?topic=account-rgs&interface=ui#rename_rgs).

**Comment by hooznora** [comment]
Hey @TusharPuri10,
If you have any other details to add regarding your issue, please reopen this issue with the details. Thank you!
