### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bschrammIBM** [ibm-cloud-docs/account#26]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The link in this text is broken 
**For more information, see User management for enterprises.**

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-what-is-enterprise#enterprise-access

3. Do you have a suggestion about how to resolve the issue?

**Comment by KentHall2018** [comment]
The doc has been updated and the link was removed.
