### ISSUE TITLE
Sort and arrange IAM Roles and Action

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/account#26]
On the page IAM Roles and Actions available at https://cloud.ibm.com/docs/account?topic=account-iam-service-roles-actions&interface=ui, I would sort roles per alphabetic order. It feels weird to start with Statum and ViziVault!!

I would even break it dow by IBM services and Third Party Services.

**Comment by mekaufman** [comment]
@lionelmace Thank you for the feedback. We do have an open issue to make improvements to this page that I will send your way.
