### ISSUE TITLE
ibm cloud dashbored

### ISSUE THREAD

**Issue by Velmurugan24** [ibm-cloud-docs/account#27]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by addison-martin1** [comment]
Hi @Velmurugan24, 

If your problem persists, please open another issue with details about the problem.
