### ISSUE TITLE
cant able to login 

### ISSUE THREAD

**Issue by adelinejane** [ibm-cloud-docs/account#27]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing? can't able to  log in, once I type my id and password  it returns to the id page

2. Is this issue in reference to a specific page? If so, please provide a link.
 https://login.ibm.com/authsvc/mtfim/sps/authsvc?PolicyId=urn:ibm:security:authentication:asf:basicldapuser&Target=https%3A%2F%2Flogin.ibm.com%2Foidc%2Fendpoint%2Fdefault%2Fauthorize%3FqsId%3D3160d0f5-d4ee-4133-bb51-37bc15528ded%26client_id%3DZWVjMWZiMzQtZGNiMi00

3. Do you have a suggestion about how to resolve the issue? no

**Comment by hlucey** [comment]
Hello @adelinejane--

Are you still experiencing log in issues? If so, I recommend reviewing the following IBM Cloud Support document, [Can't log in to my account](https://www.ibm.com/support/pages/cant-log-my-account). 

Thank you!
