### ISSUE TITLE
CF Orgs- known issues limitations IAM

### ISSUE THREAD

**Issue by benlopez1** [ibm-cloud-docs/account#28]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Limits for total CF Orgs in an account is not on the IAM known limitations page. Customer BMC has encounted the limit and asked why it is not documented. 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-known-issues

3. Do you have a suggestion about how to resolve the issue?
Please update docs to include limit of CF Orgs in an account (500)

**Comment by KentHall2018** [comment]
I updated the docs to reflect this change. Thanks @benlopez1 !
