### ISSUE TITLE
Login using CLI with newly created account fails with Code: BXNIM0602E, message: The credentials you entered for the user 'xxxx are incorrect.

### ISSUE THREAD

**Issue by Blindfreddy** [ibm-cloud-docs/account#29]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

After creating an IBM Cloud account, login via the CLI using username / password fails with error message ```Code: BXNIM0602E, message: The credentials you entered for the user 'xxxxxxx' are incorrect.```, despite entering correct credentials.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-ts_logintoibm

3. Do you have a suggestion about how to resolve the issue?

Seems that this is due to MFA Default to disable username / password login as described here:  https://stackoverflow.com/questions/76598530/unable-to-login-in-ibm-cloud-from-cli/77754626#77754626

I suggest to modify the error message, adding to it the following text:  'This may be caused by account authentication settings' or similar.

**Comment by addison-martin1** [comment]
Hi @Blindfreddy, you might have to wait 24 hours after creating an account to log into the CLI. Please try again later. If you try again and the problem persists, please let me know here.

**Comment by hooznora** [comment]
Hey @Blindfreddy,
Could you please confirm that your issue has been resolved? 
Thank you!

**Comment by hooznora** [comment]
Hey @Blindfreddy,
If you have any other details to add regarding your issue, please reopen this issue with the details. Thank you!
