### ISSUE TITLE
What are the supported account types on which Feature codes can be applied to?

### ISSUE THREAD

**Issue by Ketcomp** [ibm-cloud-docs/account#3]
1. What are the details of the issue you're experiencing?
> It is not clear what types of accounts support feature code application. Can Lite PayGo and Subscription accounts apply feature code? 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-codes 

3. Do you have a suggestion about how to resolve the issue?
With this (https://cloud.ibm.com/docs/account?topic=account-accounts) page as the source of truth, we could specify which account types can apply which types of codes. Something like: 

Promo type\Account type | Lite | PayGo | Subscription | Enterprise account
--- | --- | --- |  --- | ---
$-credit promo code | No | Yes | Yes | Yes*
Feature code | ? | ? |  ? | ? 

etc.

**Comment by hooznora** [comment]
Hey @Ketcomp, 

Thank you for reaching out regarding this! I opened a [docs issue](https://github.ibm.com/Bluemix/docs/issues/8638) about this and will track the updates there! I'm closing this one, and if there is any additional comment or suggestion, please comment under the docs issue.
