### ISSUE TITLE
Docs need to be updated for Financial Services as they show HP DBaaS in many of the architecture diagrams

### ISSUE THREAD

**Issue by seenusuvarna** [ibm-cloud-docs/account#3]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

https://cloud.ibm.com/docs/framework-financial-services?topic=framework-financial-services-best-practices#best-practices-financial-services-regions

1. What are the details of the issue you're experiencing?
The diagrams for ref arch are no longer correct with the deprecation of HP DBaaS.  They should all be updated and show how to get FS Certified.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/framework-financial-services?topic=framework-financial-services-best-practices#best-practices-financial-services-regions
Linking to ref arch: https://cloud.ibm.com/docs/framework-financial-services?topic=framework-financial-services-vpc-architecture-about
needs to be updated
4. Do you have a suggestion about how to resolve the issue?
Update all references as how to maintain FS Certification with the deprecation of HP DBaaS

**Comment by mekaufman** [comment]
@seenusuvarna I've opened an issue here https://github.com/ibm-cloud-docs/framework-financial-services/issues/7 for the correct team to get the issue addressed. Thank you for your feedback.
