### ISSUE TITLE
FAQ for support if account is terminated

### ISSUE THREAD

**Issue by ileneruth** [ibm-cloud-docs/account#30]
I have a recommendation for another FAQ. In the event that a customer has terminated an account, but needs to request access to data or has some other question, how can they get support.  

I think the options are:

1. If you have an Enterprise account, you can use support from another account in the Enterprise
2. Phone, but which number?  +1-866-403-7638?
3. This link: https://watson.service-now.com/x_ibmwc_open_case_app.do#!/create

Thanks,
   Ilene.

**Comment by addison-martin1** [comment]
Hi @ileneruth, 

Thank you for the suggestion. Our team is evaluating this use case and will follow up with questions moving forward.
