### ISSUE TITLE
Unable to log into my IBM cloud account

### ISSUE THREAD

**Issue by Adnazifi** [ibm-cloud-docs/account#31]
Hello, 

I am taking a coursera course, Building AI Application with Watson APIs. I enrolled in an online degree program. This has resulted in my abandoning the course for over six months, now I want to continue but could not log in with the same email I was using. I even reset the password but still, it's not working. The email is adnazeef@gmail.com. Initially, I was using adnazifi@gmail.com, but when I enrolled in this course, I was asked to abandon it and create it (adnazeef@gmail.com). Can someone reset the former one or both of them, please?

**Comment by hooznora** [comment]
Hello @Adnazifi,
Thank you for reaching out to us! For login-related issues, I'd recommend contacting [IBM Cloud Support](https://www.ibm.com/cloud/support). You can find some more information about getting support in the [Using the Support Center](https://cloud.ibm.com/docs/get-support?topic=get-support-using-avatar) documentation.

**Comment by Adnazifi** [comment]
Thank you, I will do that.
