### ISSUE TITLE
I am facing issue during working on watsonx Assistant, No resource group available

### ISSUE THREAD

**Issue by rajeshcourse** [ibm-cloud-docs/account#32]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

I am facing issue during working on watsonx Assistant, No resource group available, a message popup as 
**Looks like you don't have permission to add the instance to any resource group in this account. Contact the account owner to be assigned an Editor or Administrator role on a resource group in the account.** 

please resolve this issue so that i can complete the remaining assignment
Thanks

**Comment by hooznora** [comment]
Hey @rajeshcourse,
Thank you for reaching out about your issue! For watsonx Assistant related issues, I'd recommend reviewing the [FAQs for watsonx Assistant](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-watson-assistant-faqs) and the [watsonx Assistant Getting help](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-troubleshoot) documentations.

**Comment by rajeshcourse** [comment]
Dear Nora Anna Hooz
I have gone through with all the resources you have shared but not able to
find the solution of my problem for that i am sharing a screenshot of the
issue while working on Watsonx Assistant,
[image: image.png]

**Comment by hooznora** [comment]
Dear @rajeshcourse,
I apologize for the delayed response! Unfortunately, the image that you shared above is not displaying for me. Are you the owner of the account in which you're working on Watsonx Assistant? If not, did you contact the account owner for the necessary permissions? 
If you're the owner of the account in which you're working, I'd recommend creating a support case about this issue by following the steps in the [watsonx Assistant Getting help](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-troubleshoot) documentation.

**Comment by hooznora** [comment]
Hey @rajeshcourse,
If you have any other details to add regarding your issue, please reopen this issue with the details. Thank you!
