### ISSUE TITLE
I can not login to my IBM cloud account

### ISSUE THREAD

**Issue by emamheba** [ibm-cloud-docs/account#32]
when i try to log in i get this message 
Upgrade cannot be performed

Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by addison-martin1** [comment]
Hi @emamheba, I'm sorry you're experiencing difficulties upgrading your account. For information about this issue, see [Why can't I upgrade my account?](https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cc-error-messages#ts-upgrade-fail).

**Comment by emamheba** [comment]
I check all credit info and all it is correct why i can not access my
account

**Comment by addison-martin1** [comment]
@emamheba Since it seems like this error continues to occur, you can contact [IBM Cloud Support](https://cloud.ibm.com/unifiedsupport/supportcenter).
