### ISSUE TITLE
Unable to upload profile picture "This file is too large."

### ISSUE THREAD

**Issue by pwmcmaho** [ibm-cloud-docs/account#33]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

**Unable to upload profile picture ...  The image I am trying to upload is 147kb JPEG that is 300px X 300px**

2. Is this issue in reference to a specific page? If so, please provide a link.

**https://cloud.ibm.com/user**

4. Do you have a suggestion about how to resolve the issue?

**Validate the size / constraints related to the profile picture and communicate that information in the error message.**

**Comment by addison-martin1** [comment]
Hi @pwmcmaho, 

The maximum file size for a profile picture is 100 KB. Thank you for your suggestion, we are working on a more helpful error message.
