### ISSUE TITLE
Typo in the Doc :  'IMBid user' needs to be replaced with 'IBMid user'

### ISSUE THREAD

**Issue by bcgong** [ibm-cloud-docs/account#34]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
There is a typo in the documentation. 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-federated_id&interface=ui#login-ibmid-users

3. Do you have a suggestion about how to resolve the issue?
'IMBid user' needs to be replaced with 'IBMid user'

**Comment by hooznora** [comment]
Hey @bcgong,
Thank you for opening this issue! The typo has been fixed both in the staging and production docs: https://cloud.ibm.com/docs/account?topic=account-federated_id&interface=ui#login-ibmid-users

Closing this issue!
