### ISSUE TITLE
English version of enlarged "Figure 1. Account components and systems" Needed

### ISSUE THREAD

**Issue by GingerNinja901** [ibm-cloud-docs/account#35]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
From this page - https://cloud.ibm.com/docs/account?topic=account-overview, when clicking on "Figure 1. Account components and systems" to enlarge the diagram, the large diagram is written in Spanish > https://cloud.ibm.com/docs/api/content/account/images/account_diagram.svg

<img width="1231" alt="Screen Shot 2021-05-17 at 17 13 23" src="https://user-images.githubusercontent.com/43808469/118446717-4b54dd00-b733-11eb-8589-358215fc0d4d.png">

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-overview
https://cloud.ibm.com/docs/api/content/account/images/account_diagram.svg

3. Do you have a suggestion about how to resolve the issue?
Although the Spanish version is helpful for Spanish speakers, the English version of enlarged diagram is needed for bigger audiences.

**Comment by KentHall2018** [comment]
@GingerNinja901 thank you for bringing this up. Our team is looking into it.

**Comment by KentHall2018** [comment]
fixed the issue by removing the enlarging capability. The API call wasn't 100%.
