### ISSUE TITLE
You can't create a support case when your account is suspended

### ISSUE THREAD

**Issue by jlsjonas** [ibm-cloud-docs/account#35]
1. What are the details of the issue you're experiencing?

    My account got suspended days after creation before I even had the time to start using the service, the docs refer to the support site for help, which doesn't work without an active account...
    > To resolve the issue, [create a support case](https://cloud.ibm.com/docs/get-support?topic=get-support-open-case)

2. Is this issue in reference to a specific page? If so, please provide a link.

    https://cloud.ibm.com/docs/account?topic=account-resource_inactive
    
    Also on https://cloud.ibm.com/docs/get-support?topic=get-support-using-avatar :
    
    > If you can't log in to your account, start a chat by going to the [IBM Cloud Support](https://www.ibm.com/cloud/support) page and clicking Let's talk.
    
    Which again redirects you to the login page before you can initiate a conversation

3. Do you have a suggestion about how to resolve the issue?
      1. Don't randomly suspend accounts without reason
      2. Allow an accountless entrypoint to chat for account issues

**Comment by addison-martin1** [comment]
HI @jlsjonas, 

Thank you for bringing this up. We will pass this along to the support team for improvement.
