### ISSUE TITLE
HIPAA BAA for non covered entities needs to be added

### ISSUE THREAD

**Issue by seenusuvarna** [ibm-cloud-docs/account#37]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The contact information at https://cloud.ibm.com/docs/account?topic=account-enabling-hipaa under the IMPORTANT section does nothing.  Should have the Lawyer BAA be available for non-covered entities to fill out and then send to IBM Sales or IBM Cloud to sign and return a copy so that the non-covered entity dealing with HIPAA data can activate the feature.  Then the Console needs to be updated as well since it is confusing as the wording does not work for non-covered entities.  If needed please look me up on IBM Internal and I can give the information about how this might cause an issue.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-enabling-hipaa

3. Do you have a suggestion about how to resolve the issue?
I have a suggestion and was documented in the above item 1, but basically have the BAA available for non-covered entities to fill out and submit and then have a quick turnaround for them.  Then update the console on IBM Cloud to reflect changes needed for activating the feature on IBM Cloud.  Contact me on IBM Internal if more info is needed.

**Comment by mekaufman** [comment]
Thank you for the feedback @seenusuvarna. We will work with you internally to get this addressed.
