### ISSUE TITLE
Broken Link on https://cloud.ibm.com/docs/account?topic=account-what-is-enterprise

### ISSUE THREAD

**Issue by bschrammIBM** [ibm-cloud-docs/account#37]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
For more information, see [User management for enterprises](https://cloud.ibm.com/docs/account?topic=account-enterprise-access).
Link leads to "Content isn't available."

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-what-is-enterprise

3. Do you have a suggestion about how to resolve the issue?
Add a valid URL to correct content.

**Comment by hlucey** [comment]
Hi @bschrammIBM-- 

Thank you for taking the time to submit feedback on the IBM Cloud documentation. The broken link has been updated. 

Thank you for your time! 
Haley Lucey
