### ISSUE TITLE
Not able to finish my lab work in IBM cloud.

### ISSUE THREAD

**Issue by richa11101982** [ibm-cloud-docs/account#38]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
Hi @richa11101982. Please provide some details and reopen the issue, if you're experiencing an issue with docs.

**Comment by richa11101982** [comment]
I am not able to login in my IBM I'd and create a free instance with Lite package to finish my lab work in DB2.
