### ISSUE TITLE
Remove reference to Lockbox - no longer provided

### ISSUE THREAD

**Issue by markpokane** [ibm-cloud-docs/account#38]
Page: https://cloud.ibm.com/docs/account?topic=account-email-prefs#required-user-notification-access
Issue: It mentions **Manage Lockbox**. We no longer offer this service so should be removed

![image](https://user-images.githubusercontent.com/33838544/119471230-ffacbf80-bd40-11eb-84e3-44df05358531.png)

**Comment by el-moshme** [comment]
@markpokane can I ask, why is this still in IAM in production if you want it removed from docs? I followed the instructions linked and 

![Uploading Screen Shot 2021-05-25 at 3.13.59 PM.png…]()

**Comment by el-moshme** [comment]
<img width="1415" alt="Screen Shot 2021-05-25 at 3 13 43 PM" src="https://user-images.githubusercontent.com/27785752/119555466-e40ade80-bd6b-11eb-9afc-290a10fa2fd5.png">

**Comment by markpokane** [comment]
Hi Nancy... excellent question.. Lockbox support was ended August 20, 2018 so I'm surprised it is still listed. I'd check with our Offering Management to be sure.

**Comment by hlucey** [comment]
Hi @markpokane and @el-moshme, 

Manage Lockbox has been removed from our docs. We are in the process of removing this from the console. Thanks for bringing this to our attention!

**Comment by markpokane** [comment]
You're welcome Haley
