### ISSUE TITLE
IBM cloud feature code doesn't work

### ISSUE THREAD

**Issue by WoojinParkSoftware** [ibm-cloud-docs/account#38]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
My featured code to register in ibm cloud doesn't work.
2. Is this issue in reference to a specific page? If so, please provide a link.

Error
We apologize for the inconvenience, but we were unable to complete your account creation request. Please check the information you provided and try again later. Thank you.
Code: b4ad748b-5d16-4923-9151-90e692e34366

3. Do you have a suggestion about how to resolve the issue?
I'm not sure but maybe new code?

**Comment by hooznora** [comment]
Hi @WoojinParkSoftware,
Thank you for reaching out to us and sorry for the delayed reply! Please find some more information about applying feature codes in the following documentation: 

- [Why can't I apply a feature code?](https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cannot-apply-feature-code)
- [Applying feature codes](https://cloud.ibm.com/docs/account?topic=account-codes)
- [FAQs about accounts](https://cloud.ibm.com/docs/account?topic=account-accountfaqs#create-account)

For receiving further help, I'd recommend contacting [IBM Cloud Support](https://www.ibm.com/cloud/support). You can find some more information about getting support in the [Using the Support Center](https://cloud.ibm.com/docs/get-support?topic=get-support-using-avatar) documentation.

**Comment by hlucey** [comment]
Hello @WoojinParkSoftware, 

We hope the information Nora provided helped. If you are still experiencing an issue, please reopen this issue with details. 

Thanks!
