### ISSUE TITLE
IAM Doc should explain the Account Management Hierarchy

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/account#39]
I understand there is a hierarchy in the Account Management access policy.
Yet, this is hard to guess this hierarchy for a user.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/12241613/217872038-2ede39fa-878e-471c-a5d5-25a8bf0bb5fb.png">

The recommendation would be to have this hierarchy documented somewhere in the doc:
https://cloud.ibm.com/docs/account?topic=account-iamoverview

Here is the hierarchy (hopefully this is correct!) 
- All Identity and Access enabled services
- Account - All Account Management services
    - All IAM Account Management services
        - IAM Access Management Service
        - IAM Identity Service
        - IAM Access Groups Service
    - Billing
    - Support Center
    - Catalog Management
- Global Resource Catalog
- Enterprise
- Resource group only

**Comment by addison-martin1** [comment]
Hey @lionelmace, thanks for alerting us to this issue! We've noted it in on our internal issue tracking system and will follow up with you there!
