### ISSUE TITLE
Content for "Creating and working with service IDs" incomplete

### ISSUE THREAD

**Issue by michaelbeck** [ibm-cloud-docs/account#39]
The content for docs page [Creating and working with service IDs](https://cloud.ibm.com/docs/account?topic=account-serviceids) is incomplete and even includes different topics depending on the interface selected. Fun fact: For CL even though the title says 'Creating and ...' the content doesn't include how to create a service ID ;-)

Topics that need to be covered for all interfaces are:
1. Create
2. Read / list
3. Update
4. Lock
5. Unlock
6. Delete

**Comment by hooznora** [comment]
Hey @michaelbeck,
Thank you for creating this issue! I opened the following internal issue on our docs board to make and track the necessary updates: https://github.ibm.com/Bluemix/docs/issues/10592

If you have any other feedback to add, feel free to add it to the internal issue! I'm closing this issue.
