### ISSUE TITLE
Page not found: https://cloud.ibm.com/docs/account?topic=account-accessing

### ISSUE THREAD

**Issue by meiaus** [ibm-cloud-docs/account#4]
I was navigating this page and inside the page, 
https://cloud.ibm.com/docs/account?topic=account-signup

a Troubleshooting link is attached as follows:

![image](https://user-images.githubusercontent.com/27024803/79145050-94df3580-7d85-11ea-8b6c-f91ffeca036a.png)

But it returned as Page not Found.

Please check.
Thanks.

**Comment by hlucey** [comment]
Link updated to point to the first TS entry for accessing IBM

**Comment by meiaus** [comment]
Great. Thanks.
fyi - In https://cloud.ibm.com/docs/account?topic=account-ts_logintoibm, 

![image](https://user-images.githubusercontent.com/27024803/79248819-f4028000-7e41-11ea-82c5-539fa21cad65.png)
