### ISSUE TITLE
change my resource to resource list

### ISSUE THREAD

**Issue by chrisverrett** [ibm-cloud-docs/account#4]
hello, 

on this link
https://cloud.ibm.com/docs/account?topic=account-rgs&interface=ui#view_rg_resources

 please change "My Resources" to "Resource List" to match the verbiage in the portal

Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
@chrisverrett Thank you for reporting this. Updates have been committed.
