### ISSUE TITLE
IBM APPLICATIONS TECHNOLOGY 123

### ISSUE THREAD

**Issue by MFALHI** [ibm-cloud-docs/account#40]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?
Software

**Comment by KentHall2018** [comment]
@MFALHI I see that you answered `Software` for the suggestion to resolve question. Is there anything more that you want to add for this issue about the documentation?

**Comment by KentHall2018** [comment]
@MFALHI  I'm going to close this issue. Reopen the issue if you have any details that you want to bring up or feel free to open another issue for this repo. thanks!
