### ISSUE TITLE
IBM

### ISSUE THREAD

**Issue by shahriar1990** [ibm-cloud-docs/account#41]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by KentHall2018** [comment]
@shahriar1990 were you trying to open an issue regarding the documentation? If so, answer the provided question and we'll try to resolve it. 

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by KentHall2018** [comment]
@shahriar1990 I'm going to close this issue. Reopen the issue if you have any details that you want to bring up or feel free to open another issue for this repo. thanks!
