### ISSUE TITLE
Can't get verification code

### ISSUE THREAD

**Issue by ANetTow** [ibm-cloud-docs/account#43]
I am trying to sign up for an IBM Cloud account through a Data Science course on Coursera, but I have not received an email verification code. My spam folder is empty and "resend code" is not effective. The "Help" link sent me here, so I hope this gets to someone who can help.  

The link in question is: 

https://cloud.ibm.com/registration?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCourses-OpenSourceToolsForDataScienceCoursera-2022-01-01&featureCode=d1db7a200198cde93bb72f673d224526

**Comment by jenschlot** [comment]
@ANetTow we checked with the account team and they think the verification codes function is working. Could you try to sign up again?

**Comment by ANetTow** [comment]
I eventually received all the codes 2 days later but of course they were expired. I was able to get a login with verification code using an alternative email address.
Thank you!
Annette

    On Tuesday, May 14, 2024 at 10:43:27 AM PDT, Jenifer Schlotfeldt ***@***.***> wrote:  
 
 


@ANetTow we checked with the account team and they think the verification codes function is working. Could you try to sign up again?

**Comment by hlucey** [comment]
@ANetTow 

I'm glad you were able to get a verification code. If you experience any other issues, reopen this issue with additional details. 

Thanks!
