### ISSUE TITLE
TOTP and multiple accounts

### ISSUE THREAD

**Issue by mysteq** [ibm-cloud-docs/account#43]
I have an IBMid with two accounts connected to it, which I added TOTP 2FA on recently, which is according to the short description on "https://cloud.ibm.com/docs/account?topic=account-login-settings#MFA". 
I used "Google Authenticator" for the TOTP.
My issue is that when I added the TOTP for account #2 it seems to just replace the TOTP for account #1, which ended up with me basically locking myself out of one account, and needing an owner for the account to disable it. I'm assume this happened because the two TOTP setups get's the same default name in Google Authenticator "IBM Cloud (<IBMid>).
Did I manage to do something wrong, or is this the default behaviour and by design? If the latest it would probably be nice to mention in the documentation a warning to remember to rename the first TOTP in authenticator app before adding any more?

**Comment by mekaufman** [comment]
@mysteq Thank you for your feedback. You are correct that if you plan to set up TOTP with the same authenticator app for more than one account, then you will need to give a unique name for the first and even subsequent TOTP set ups. We are working on an update around this use case.

**Comment by hlucey** [comment]
Updates are now reflected: https://cloud.ibm.com/docs/account?topic=account-login-settings#MFA.
