### ISSUE TITLE
I didn't get any code 

### ISSUE THREAD

**Issue by sivaranjani098** [ibm-cloud-docs/account#44]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by hlucey** [comment]
Hello @sivaranjani098-- 

Can you provide more information about the issue you are experiencing? I also suggest [contacting support](https://test.cloud.ibm.com/docs/get-support?topic=get-support-open-case&interface=ui#creating-support-case)  and opening a support case.

If you have specific feedback about an issue you're experiencing with documentation, please reopen this issue with the details.

Thanks!
