### ISSUE TITLE
NodeJS code snippet is wrong, needs update

### ISSUE THREAD

**Issue by saikumar1607** [ibm-cloud-docs/account#44]
**URL** - https://cloud.ibm.com/docs/account?topic=account-iamtoken_from_apikey#iamtoken_from_apikey

**Screenshot**
![image](https://user-images.githubusercontent.com/75735146/123294525-903e1180-d532-11eb-88ff-bf4f26558bfa.png)

1. What are the details of the issue you're experiencing?
The NodeJs code snippet is of `BearerTokenAuthenticator`. It should be changed to `IamAuthenticator `

2. Is this issue in reference to a specific page? If so, please provide a link.
Check above

3. Do you have a suggestion about how to resolve the issue?
Reach out to slack channel `#ibm-sdk-generation` in the IBM Cloud Platform workspace for the correct code snippet.
Or you can directly reach out to phil_adams@us.ibm.com who is the maintainer of node-core-sdk (from where the snippet is copied)

**Comment by KentHall2018** [comment]
created a different issue to complete this work: [NodeJS code snippet is wrong #7952](https://github.ibm.com/Bluemix/docs/issues/7952)

**Comment by KentHall2018** [comment]
@saikumar1607 the documentation was updated with your suggestion and the changes were moved to production. Thanks for your help!

**Comment by saikumar1607** [comment]
yeah, thank you Kent.

checked the snippet. It's updated and is the correct one. 👍
