### ISSUE TITLE
Denied services

### ISSUE THREAD

**Issue by datocrats-org** [ibm-cloud-docs/account#47]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
I cannot update my account registration to a paid account. I sent several emails to verify@us.ibm.com only to be told we have reviewed your account/transaction and will not be able to offer services. No further information will be disclosed regarding this matter.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-accounts#accounts

3. Do you have a suggestion about how to resolve the issue?
Do not deny services arbitrarily and without explanation.

**Comment by hlucey** [comment]
Hi @datocrats-org are you an IBMer? If so, please reach out to me internally and I can help route you to the right team for this issue.

If you're not an IBMer, please open a support case here and our support team can get you squared away: https://cloud.ibm.com/unifiedsupport/supportcenter.

**Comment by datocrats-org** [comment]
Hi @hlucey no I am not IBMer.  It says my account is blocked so I get logged out of the support link you provided 
![image](https://user-images.githubusercontent.com/12563261/73235139-0e8a5e80-415b-11ea-901c-cfaf231d61aa.png)

**Comment by hlucey** [comment]
@datocrats-org, 

After speaking with the support team, contacting verify@us.ibm.com is the correct course of action. I apologize I could not help further. I hope your problem is resolved shortly!
