### ISSUE TITLE
while trying to create a new account after fill everything and check the privacy notice's checkbox, I still coud not create an account and it gives me this error: Error Your account cannot be created at this time. Code: b49929fd-364a-4354-8044-e661f6ecca15

### ISSUE THREAD

**Issue by Ahmed-Farage** [ibm-cloud-docs/account#5]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by hooznora** [comment]
Hello @Ahmed-Farage,
I suggest looking at our [FAQs about accounts documentation](https://cloud.ibm.com/docs/account?topic=account-accountfaqs) where you can find information about why your account cannot be created and what to do if you run into any issues. 
Please let us know if you need further help!
