### ISSUE TITLE
IBM Cloud Document Issue: Enabling VRF and service endpoints

### ISSUE THREAD

**Issue by rajinib** [ibm-cloud-docs/account#5]
1. What are the details of the issue you're experiencing?
In the document "Enabling VRF and service endpoints" several links are broken.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-vrf-service-endpoint&interface=ui

3. Do you have a suggestion about how to resolve the issue?
I believe the path of these broken links needs to be corrected to fix it.

For example, the broken link is,
[Databases for Redis service endpoints integration](https://cloud.ibm.com/docs/services/databases-for-redis?topic=cloud-databases-service-endpoints)

There are more such broken links in this document "Enabling VRF and service endpoints."

**Comment by mekaufman** [comment]
@addison-martin1 Can you please take a look. 

@rajinib Thank you for the feedback.

**Comment by addison-martin1** [comment]
I updated the broken links. Thank you for bringing this to our attention.
