### ISSUE TITLE
Remove the page "Monitoring login sessions for other users in your account"

### ISSUE THREAD

**Issue by michaelbeck** [ibm-cloud-docs/account#50]
### Which topic are you reporting about?

https://github.com/ibm-cloud-docs/account/blob/9638339ff926d5b09c518e20e8cb1d7ff7e61ff2/sessions-users.md

### What do you think needs to be updated?

The whole section needs to be removed, managing sessions for other users is not supported.

**Comment by swethaisrael** [comment]
@michaelbeck confirmed to remove the **Monitoring login sessions for other users in your account** topic from the acc repo.

**Comment by swethaisrael** [comment]
Reference PR: https://github.ibm.com/cloud-docs/account/pull/925

**Comment by michaelbeck** [comment]
Thanks for fixing!
