### ISSUE TITLE
>add Readonly.md & .getconfigmanifest.sc.rx.md v1.0.1 - v13.0.1

### ISSUE THREAD

**Issue by IamK51** [ibm-cloud-docs/account#51]
> _No description provided._

#50 TOR-6G : Dragon.Online

_Originally posted by @IamK51 in https://github.com/ibm-cloud-docs/account/pull/50#issuecomment-892727250_

**Comment by hooznora** [comment]
The above-mentioned PRs have been closed, closing this issue.
