### ISSUE TITLE
EU-Support is no longer a filter in the IBM Catalogue

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/account#52]
On the page : https://cloud.ibm.com/docs/account?topic=account-eu-supported
We state:
"After you enable the setting at the account level, you can use the EU Supported filter to find products that have EU-supported pricing plans. In the IBM Cloud catalog, expand the Compliance section and select EU Supported."

But "EU-Support is no longer an option as the Filter for Compliance. (It will be nice if we add this filter option to the Catalogue again)

**Comment by mekaufman** [comment]
@LarsIpsen You must turn the setting on in order to see the filter. I just tested it out in production and it works as expected:

![image](https://user-images.githubusercontent.com/13648625/132855179-406f5217-b43f-41ee-afed-0b6f5fa46d4b.png)
