### ISSUE TITLE
Documentation issue : Invoking IBM Cloud service APIs

### ISSUE THREAD

**Issue by benblan** [ibm-cloud-docs/account#6]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
In the documentation, in section 'Passing an IBM Cloud IAM token to authenticate with a service's API', in reviewing example, in number 2 : Prefix the IAM access token with the literal Bearer: Bearer eyJhbGciOiJSUzI1Ng... 
The first "Bearer:" should be removed.
3. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-iamapikeysforservices&interface=ui&code=curl
4. Do you have a suggestion about how to resolve the issue?
The first Bearer: should be removed.

**Comment by addison-martin1** [comment]
HI @benblan, 

Thank you for bringing this to our attention. This update has been made.
