### ISSUE TITLE
Enterprise Accunt for IBM Internal Chargeback

### ISSUE THREAD

**Issue by ashwin49** [ibm-cloud-docs/account#6]
Team,

I am an IBM employee working for Offering Development in GTS.
We need more documentation on how to setup an Enterprise Account for internal charge-backs, can you help? Can you please post more documentation on how we can achieve this?

Regards,
Ashwin

**Comment by hlucey** [comment]
Hi @ashwin49, 

I'm going to reach out to you internally to resolve this issue! 

(cc:  @avery-rowe)
