### ISSUE TITLE
Link to SQl-Query example isn't working

### ISSUE THREAD

**Issue by oevers** [ibm-cloud-docs/account#6]
In the documentation for account https://cloud.ibm.com/docs/account?topic=account-serviceids
the link at the bottom
Cloud SQL Query - How to use the SQL Query REST API.
which points to https://www.youtube.com/embed/s6S4AdJItHk?rel=0
isn't working (at least for me in Germany)
When I click on play I get the message: Video unavailable
This video is unavailable.

**Comment by hlucey** [comment]
Video link updated in production.
