### ISSUE TITLE
introduction of cloud computing

### ISSUE THREAD

**Issue by Saquib0001** [ibm-cloud-docs/account#7]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?
4. how can we use IBM cloud in Education field

**Comment by mekaufman** [comment]
Hi @Saquib0001, thanks for your inquiry. Here are two pages you could check out for more about using IBM Cloud in the education field: https://www.ibm.com/cloud/education and https://www.ibm.com/cloud/learn/education

**Comment by Saquib0001** [comment]
Thank u for sharing link😊
