### ISSUE TITLE
Python sample seems wrong

### ISSUE THREAD

**Issue by jorgego11** [ibm-cloud-docs/account#7]
Hi
Why the python sample to get an IAM access token using an API Key have a reference to 'my-client-id' and 'my-client-secret' IN ADDITION to the API Key?   Every other language example does not require 'my-client-id' and 'my-client-secret'. Which seems really odd. 

```
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

authenticator = IAMAuthenticator('my_apikey')
authenticator.set_client_id_and_secret('my-client-id', 'my-client-secret');
service = ExampleService(authenticator=authenticator)

service.get_authenticator.set_disable_ssl_verification(true);
```

Page URL:  https://cloud.ibm.com/docs/account?topic=account-iamtoken_from_apikey&code=python

**Comment by addison-martin1** [comment]
Hi @jorgego11, 

Thank you for bringing this to our attention. The development team is looking into this example, and we will notify you when this is updated.

**Comment by addison-martin1** [comment]
Hi @jorgego11, 

The python code example is now updated, which you can view it here: https://cloud.ibm.com/docs/account?topic=account-iamtoken_from_apikey&code=python.
