### ISSUE TITLE
Academic accounts for IBM Cloud to test Blockchains

### ISSUE THREAD

**Issue by Geo-oxon** [ibm-cloud-docs/account#7]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by Geo-oxon** [comment]
I'm trying to experiment with deploying a blockchain network using IBM Cloud as an academic.  But I'm really struggling on how to do this. I believe that it's free, but need some guidance to get started.

**Comment by hlucey** [comment]
Hello @Geo-oxon , 

IBM Cloud trial accounts are available for faculty and students at accredited academic institutions. To qualify for a trial account, go to [Harness the Power of IBM](https://my15.digitalexperience.ibm.com/b73a5759-c6a6-4033-ab6b-d9d4f9a6d65b/dxsites/151914d1-03d2-48fe-97d9-d21166848e65/home) and validate your institution credentials. Unlike Lite accounts, trial accounts expire after their trial period ends.

If you still have questions, please open a support case here and our support team can get you squared away: https://cloud.ibm.com/unifiedsupport/supportcenter.
