### ISSUE TITLE
broken link to authentication account settings 

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/account#8]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
A link to get to more details is broken and leads to a non available content

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-enablemfa#enabling
![image](https://user-images.githubusercontent.com/20317763/144092706-8a95a837-a73f-49fe-99c4-252772d5cf90.png)

3. Do you have a suggestion about how to resolve the issue?
I guess the content had been moved I do not know where the content for https://cloud.ibm.com/docs/account?topic=account-mysecurity is located now.

**Comment by mekaufman** [comment]
@stschmitt Thanks for reporting this issue. We're fixing it now. The page you're looking for is located here: https://cloud.ibm.com/docs/account?topic=account-verification-authentication
