### ISSUE TITLE
Login Issues on IBM Cloud Portal 

### ISSUE THREAD

**Issue by nelliemuller** [ibm-cloud-docs/account#9]
After contacting IBM support for 2 days, I'm still not able to log in. The system is keeping me in a loop. 

I do not receive a link to reset my password from IBM Cloud portal. I only receive a reset option from IBMid on IBM Security Verify where I get the error message when I try to log in after resetting my password saying the account (not mine) was disabled by admin (me). 

I then receive messages asking me to take action from the portal (where I am unable to log in). The messages relate to logging in. 

Anyone else experience this on IBM Cloud portal?

**Comment by mekaufman** [comment]
@nelliemuller Hi, are you still experiencing this issue? If so, could you provide some additional details like the message you're receiving?

**Comment by nelliemuller** [comment]
Thank you for asking @mekaufman. Yes, after about a week, they figured out how to fix things.
