### ISSUE TITLE
Downgrade Account Trial -> Lite

### ISSUE THREAD

**Issue by pratikgujral** [ibm-cloud-docs/account#9]
How to I downgrade my Trial account to Lite account?

**Comment by mekaufman** [comment]
Hi @pratikgujral. You can't create any new [Lite accounts](https://cloud.ibm.com/docs/account?topic=account-accounts#liteaccount) at this time. You can upgrade your trial to a pay-as-you-go or subscription account, if needed. There's some additional information about trial accounts available [here](https://cloud.ibm.com/docs/account?topic=account-accounts#trial).
