### ISSUE TITLE
issue with Doc -- https://cloud.ibm.com/docs/account?topic=account-service-endpoints-overview

### ISSUE THREAD

**Issue by noedsouz** [ibm-cloud-docs/account#9]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
the doc says 
"There is no billable or metered bandwidth charges on the private network. In the past, you were billed for egress bandwidth when talking to an IBM Cloud service."
 It should be written that it’s not billable per bandwidth, but per hours as in case for db2 

 It should be written that it’s not billable per bandwidth, but per hours
2. Is this issue in reference to a specific page? If so, please provide a link.
yes : https://cloud.ibm.com/docs/account?topic=account-service-endpoints-overview

 It should be written that it’s not billable per bandwidth, but per hours

3. Do you have a suggestion about how to resolve the issue?

 It should be written that it’s not billable per bandwidth, but per hours like for db2 
$0.0959 USD/SERVICEENDPOINT_INSTANCE_HOURS

**Comment by KentHall2018** [comment]
Created a PR for this issue:
  - [update service-endpoints.md #195](https://github.ibm.com/cloud-docs/account/pull/195)
