### ISSUE TITLE
IBM Cloud VSI options are not clarified in regards to VPC Gen1 and Gen2

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/account#9]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The documentation is not going on how VPC Gen1 and VPC Gen2 differ here

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-service-endpoints-overview

3. Do you have a suggestion about how to resolve the issue?
Please add some clarity on how to connect if a VSI is running in Gen1 vs Gen2

**Comment by mekaufman** [comment]
@stschmitt Thank you for the feedback. I've sent you an email with a link to an internal issue I opened that you can track as we do some research and updates based on your feedback.
