### ISSUE TITLE
Document/Provide API for Auditing Access Reports

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/account#9]
1. What are the details of the issue you're experiencing?
The document shows how to get access reports from the Web Console, but if you had hundreds of resources this would take a long time.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/account?topic=account-access-report

3. Do you have a suggestion about how to resolve the issue?
If there is an API endpoint to get these reports, it can make full audits much easier to do.

**Comment by mekaufman** [comment]
@chanster At this time, you can only obtain these reports through the console.
