### ISSUE TITLE
my payment is always get rejecting

### ISSUE THREAD

**Issue by SreangSeanghorn** [ibm-cloud-docs/account#9]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by hooznora** [comment]
Hello @SreangSeanghorn,
I'm sorry to hear about this issue! Please take a look at our [FAQs documentation about accounts](https://cloud.ibm.com/docs/account?topic=account-accountfaqs) for guidance on how to solve the problem. 
If you have any other questions or issues, don't hesitate to reach out again!
